on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - '*'
jobs:
  update-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3.8
      - run: sudo apt-get install -y gettext
      - run: pip install transifex-client requests
      - uses: actions/checkout@master
      - run: echo -e '[https://www.transifex.com]\napi_hostname = https://api.transifex.com\nhostname = https://www.transifex.com\nusername = api' > $HOME/.transifexrc
      - run: ./manage_translation.py fetch
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - run: ./manage_translation.py recreate_readme
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - run: git config --local user.email 'maciej.olko@gmail.com'
        name: Run git config --local user.email '…'
      - run: git config --local user.name "GitHub Action's update-translation job"
      - run: git add .
      - run: git commit -m 'Update translation from Transifex' || true
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build-translation:
    runs-on: ubuntu-latest
    needs: ['update-translation']
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3.8
      - uses: actions/checkout@master
        with:
          repository: python/cpython
          ref: 3.8
      - run: make venv
        working-directory: ./Doc
      - uses: actions/checkout@master
        with:
          path: Doc/locales/pl/LC_MESSAGES
      - run: git pull
        working-directory: ./Doc/locales/pl/LC_MESSAGES
      - run: make -e SPHINXOPTS="-D language='pl' -D gettext_compact=0 -W --keep-going" html
        working-directory: ./Doc
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: Doc/build/html
  commit-build:
    runs-on: ubuntu-latest
    needs: ['build-translation']
    steps:
      - uses: actions/checkout@master
      - run: git pull
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - run: rm -r docs
      - run: mv build docs
      - run: touch docs/.nojekyll
      - run: git config --local user.email 'maciej.olko@gmail.com'
        name: Run git config --local user.email '…'
      - run: git config --local user.name "GitHub Action's commit-build job"
      - run: git add .
      - run: git commit -m 'Update translation build' || true
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
