on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - '*'
jobs:
  update-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3.8
      - run: sudo apt-get install -y gettext
      - run: pip install transifex-client requests numpy
      - uses: actions/checkout@master
      - run: cp .github/workflows/.transifexrc $HOME
      - run: ./manage_translations.py fetch
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - run: ./manage_translations.py recreate_readme
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - run: git config --local user.email 'maciej.olko@gmail.com'
      - run: git config --local user.name "GitHub Action's update-translation job"
      - run: git commit -a -m 'Update translation from Transifex' || true
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 3.8
